### PR TITLE
Prepare for CRAN release

### PR DESCRIPTION
**Pull request by lparsons**
* Updated Version, Date, and Authors in DESCRIPTION
    * Set Version to release version 0.2.4
    * Updated Date
    * Fixed Authors to properly call `person()`
    * Fixed Description to avoid starting with package name or "this package".
* Updated installation instructions
* Added NEWS.md

Addresses #16

### CODE REVIEW

**Comment by lparsons** [comment]
@XiaoyangSu and @wangyujue23 - There are a couple of items to clear up before we make the CRAN submission

1. Our roles - For each person mentioned in the Authors section of the `DESCRIPTION` file, we must specify [a three letter code specifying the role](https://r-pkgs.org/description.html#author). There are four important roles:
    * `cre`: the creator or maintainer, the person you should bother if you have problems.
    * `aut`: authors, those who have made significant contributions to the package.
    * `ctb`: contributors, those who have made smaller contributions, like patches.
    * `cph`: copyright holder. This is used if the copyright is held by someone other than the author, typically a company (i.e. the author’s employer).
The person that is the maintainer will also be handling the interactions with CRAN via email, so that is a particularly important role.

2. [Licensing and copyright](https://r-pkgs.org/license.html) In addition to authors/maintainers/contributors, we need to make sure the Copyright information is correct. I'm not sure if Princeton and/or Rutgers should be the copyright holders either, honestly, that's always been a bit vague to me.

**Comment by lparsons** [comment]
@XiaoyangSu and @wangyujue23 - I have updated the copyright information and roles section, including adding an ORCID for Xioayang and myself. Please review these changes and indicate that we are ready to submit by "accepting" the pull request. Yujue, please let me know if you have an ORCID to include.

**Review by XiaoyangSu — COMMENTED** [review]
Please add Yujue's ORCID 0000-0001-7088-1729

**Comment by lparsons** [comment]
> Please add Yujue's ORCID 0000-0001-7088-1729

@XiaoyangSu Thanks for the info, I've added the ORCID. Once I get your "accepted" review (or we fix any remaining issue you find), I'll package it up for submission to CRAN.

**Review by XiaoyangSu — APPROVED** [review]

**Pull request merged**
